import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Box from '../components/Box'

import cyberpolin from '../public/img/cyberpolin.jpeg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React & React Native developer - Full stack coder - Carlos González</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <aside>
        {/* Cyberpolin */}
        <Image src={cyberpolin} className={styles.mainPicture} width='150%' height='150%'/>
        <Box title='Carlos González'>
          <p>Javascript Expert, React & React Native profesional</p>
          <a maito='hire@cyberpolin.com'>hire@gmail.com</a>
        </Box>
        {/* Cyberpolin */}
      </aside>
    </div>
  )
}
